---
 title: Interviews with people who eat plant based foods, online shop selling handmade products made from plants. Thoughts and ideas on sustainability, bicycles, food and life.
 timezone: GMT
 collections:
   home:
     title: Home
     output: true
   noshbites:
     title: Noshbites
     output: true
   posts:
     title: Posts
     output: true
   products:
     title: Products
     output: true
   skinfood:
     title: Skinfood
     output: true
   krafttex:
     title: Kraft-Tex
     output: true
   shop:
     title: Shop
     output: true
   random-thoughts:
     title: Random Thoughts
     output: true
   uploads:
     title: Uploads
     output: true
 defaults:
 - scope:
     path: ''
     type: products
   values:
     layout: product
     permalink: "/products/:title/"
     name: ''
     price: '0.0'
     order: ''
     sku: ''
     first_image: ''
     second_image: ''
     weight: 0.0
     message: ''
     excerpt: ''
     quote: ''
     quoteperson: ''
     packsize: ''
     offer: ''
 - scope:
     path: ''
     type: posts
   values:
     permalink: "/journal/:title/"
     layout: post
     categories: ''
     assets: 
     excerpt: ''
 author: Rajiv Shah
 url: https://yomojo.co.uk
 enforce_ssl: yomojo.co.uk
 plugins:
 - jekyll-sitemap
 - jekyll-seo-tag
 permalink: pretty
 copyright: Yomojo
 description: Interviews with people who eat plant based foods, online shop selling
   handmade products such as plantbased chocolate mulberries and skincare. Thoughts
   and ideas on sustainability, life, food and news - leicester uk.
 sass:
   sass_dir: _sass
 markdown: kramdown
 redcarpet:
   extensions:
   - autolink
   - fenced_code_blocks
   - lax_spacing
   - strikethrough
   - superscript
   - tables
   - footnotes
   - highlight
 year_val: 2018
 home_banner: "/images/spelt-pizza-with-spinach-and-broccoli.jpeg"
 noshbite_banner: "/images/choc-mulberry-box.jpeg"
 github: [metadata]