---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _noshbites
  label: Noshbites
  create: all
  match: "**/*"
- type: directory
  path: _products
  label: Products
  create: all
  match: "**/*"
- type: directory
  path: _skinfood
  label: Skinfood
  create: all
  match: "**/*"
- type: directory
  path: _uploads
  label: Uploads
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _home
  label: Home
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: _uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
